/*

 BACKGROUNDGRAPHICS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 92

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __backgroundGraphics_h_INCLUDE
#define __backgroundGraphics_h_INCLUDE

/* Bank of tiles. */
#define bgGraphicsBank 1

/* Super Gameboy palette 0 */
#define bgGraphicsSGBPal0c0 6076
#define bgGraphicsSGBPal0c1 8935
#define bgGraphicsSGBPal0c2 6596
#define bgGraphicsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bgGraphicsSGBPal1c0 6076
#define bgGraphicsSGBPal1c1 8935
#define bgGraphicsSGBPal1c2 6596
#define bgGraphicsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bgGraphicsSGBPal2c0 6076
#define bgGraphicsSGBPal2c1 8935
#define bgGraphicsSGBPal2c2 6596
#define bgGraphicsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bgGraphicsSGBPal3c0 6076
#define bgGraphicsSGBPal3c1 8935
#define bgGraphicsSGBPal3c2 6596
#define bgGraphicsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bgGraphicsCGBPal0c0 27424
#define bgGraphicsCGBPal0c1 29280
#define bgGraphicsCGBPal0c2 19808
#define bgGraphicsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bgGraphicsCGBPal1c0 15168
#define bgGraphicsCGBPal1c1 14016
#define bgGraphicsCGBPal1c2 15873
#define bgGraphicsCGBPal1c3 0

/* Gameboy Color palette 2 */
#define bgGraphicsCGBPal2c0 21459
#define bgGraphicsCGBPal2c1 16365
#define bgGraphicsCGBPal2c2 13283
#define bgGraphicsCGBPal2c3 0

/* Gameboy Color palette 3 */
#define bgGraphicsCGBPal3c0 18016
#define bgGraphicsCGBPal3c1 16737
#define bgGraphicsCGBPal3c2 13537
#define bgGraphicsCGBPal3c3 0

/* Gameboy Color palette 4 */
#define bgGraphicsCGBPal4c0 6076
#define bgGraphicsCGBPal4c1 8935
#define bgGraphicsCGBPal4c2 6596
#define bgGraphicsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define bgGraphicsCGBPal5c0 6076
#define bgGraphicsCGBPal5c1 8935
#define bgGraphicsCGBPal5c2 6596
#define bgGraphicsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bgGraphicsCGBPal6c0 6076
#define bgGraphicsCGBPal6c1 8935
#define bgGraphicsCGBPal6c2 6596
#define bgGraphicsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bgGraphicsCGBPal7c0 6076
#define bgGraphicsCGBPal7c1 8935
#define bgGraphicsCGBPal7c2 6596
#define bgGraphicsCGBPal7c3 5344
/* Start of tile array. */
extern const void __bank_bgGraphics;
extern const unsigned char bgGraphics[];

#endif

/* End of BACKGROUNDGRAPHICS.H */
